[package]
name = "gitopus"
version = "0.2.0"
edition = "2021"
authors = ["Amal V S <amal.vs.engineer@gmail.com>"]
description = "A CLI tool to manage Git repositories"
license = "MIT"
repository = "https://github.com/alchemist123/gitopus"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
directories = "5.0"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
tokio = { version = "1.36", features = ["full"] }
